version: '3.8'

services:
  app:
    environment:
      - PYTHONUNBUFFERED=1
    build: "./app"
    volumes:
        - ./app:/app # Bind cartella locale ./app
        - type: bind # Bind cartella locale ./data
          source: ./data
          target: /data
          bind:
            create_host_path: true
